name: Validate

on:
  pull_request:
  push:
  release:
    types:
      - published
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - name: Validate integration repository
        uses: hacs/action@main
        with:
          category: integration

  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate Home Assistant integration
        uses: home-assistant/actions/hassfest@master
